# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: true

# Setup
title: Viraj Sinha
tagline: 
url: http://vsinha.com
baseurl: /

paginate: 5
excerpt_separator: <!--more-->


# exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# #auto: true
# safe: true
# lsi: false


# About/contact
author :
  name : Viraj Sinha
  email : root@virajos.com
  github : vsinha
  twitter : VirajSinha
  feedburner : Viraj Sinha's Blog

# Custom vars
version: 1.0.0
